package ProjectWork;

/*
 This is the UI design for the application using NetBeans
 NetBeans has drag and drop functions so the UI code generated was automatically done by NetBeans
 To read the functioning UI read the user guide from documentation
 */

import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import jess.*;

/**
 *
 * @author Divesh Badod
 */
public class pr2_DiveshBadod extends javax.swing.JFrame {

    /**
     * Creates new form pr2_DiveshBadod
     */
    public pr2_DiveshBadod() {
        initComponents();
        j1 = new JavaApplication1();
        SystemName.setText(System.getProperty("os.name"));
        if (System.getProperty("os.name").contains("Windows")){
            j1.setSystem("Windows");
        }else if(System.getProperty("os.name").contains("Mac")){
            j1.setSystem("Mac");
        }
        else {
            j1.setSystem("Linux");
        }
        architecture.setText(System.getProperty("os.arch"));
        if (System.getProperty("os.arch").contains("64")){
            j1.setsysArchitecture("64");
        }else{
            j1.setsysArchitecture("32");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JLabel jLabel1 = new JLabel();
        JPanel jPanel1 = new JPanel();
        JPanel jPanel2 = new JPanel();
        JLabel jLabel4 = new JLabel();
        SystemName = new javax.swing.JLabel();
        JPanel jPanel3 = new JPanel();
        JLabel jLabel5 = new JLabel();
        passWdYes = new javax.swing.JRadioButton();
        passWdNo = new javax.swing.JRadioButton();
        JPanel jPanel4 = new JPanel();
        firewallNo = new javax.swing.JRadioButton();
        JLabel jLabel6 = new JLabel();
        firewallYes = new javax.swing.JRadioButton();
        JPanel jPanel5 = new JPanel();
        JLabel jLabel7 = new JLabel();
        noOfUsers = new javax.swing.JComboBox<>();
        JPanel jPanel6 = new JPanel();
        JLabel jLabel8 = new JLabel();
        securityYes = new javax.swing.JRadioButton();
        securityNo = new javax.swing.JRadioButton();
        JPanel jPanel7 = new JPanel();
        JLabel jLabel9 = new JLabel();
        thirdPartyApps = new javax.swing.JTextField();
        JPanel jPanel8 = new JPanel();
        JLabel jLabel10 = new JLabel();
        architecture = new javax.swing.JLabel();
        JPanel jPanel9 = new JPanel();
        JLabel jLabel11 = new JLabel();
        anitVirusThirdParty = new javax.swing.JRadioButton();
        antiVirusWindows = new javax.swing.JRadioButton();
        antiVirusNone = new javax.swing.JRadioButton();
        JPanel jPanel10 = new JPanel();
        JLabel jLabel12 = new JLabel();
        chromeBrowser = new javax.swing.JRadioButton();
        mozillaBrowser = new javax.swing.JRadioButton();
        edgeBrowser = new javax.swing.JRadioButton();
        safariBrowser = new javax.swing.JRadioButton();
        otherBrowser = new javax.swing.JRadioButton();
        JPanel jPanel11 = new JPanel();
        JLabel jLabel13 = new JLabel();
        p2pYes = new javax.swing.JRadioButton();
        p2pNo = new javax.swing.JRadioButton();
        JButton submit = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Security Evaluation");
        setBackground(new java.awt.Color(42, 151, 255));

        jLabel1.setBackground(new java.awt.Color(72, 146, 227));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Security Evaluation");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("System you are currently using:");

        SystemName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemName.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SystemName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(262, 262, 262))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SystemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Is the machine password protected?:");

        passWdYes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passWdYes.setText("Yes");
        passWdYes.addActionListener(this::passWdYesActionPerformed);

        passWdNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passWdNo.setText("No");
        passWdNo.addActionListener(this::passWdNoActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(passWdYes)
                                .addGap(18, 18, 18)
                                .addComponent(passWdNo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passWdYes)
                                        .addComponent(passWdNo))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        firewallNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        firewallNo.setText("No");
        firewallNo.addActionListener(this::firewallNoActionPerformed);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Is the latest Firewall installed?:");

        firewallYes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        firewallYes.setText("Yes");
        firewallYes.addActionListener(this::firewallYesActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(firewallYes)
                                .addGap(18, 18, 18)
                                .addComponent(firewallNo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firewallNo)
                                        .addComponent(firewallYes))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("How many users have access to this machine?:");

        noOfUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "More" }));
        noOfUsers.setPrototypeDisplayValue("1");
        noOfUsers.addActionListener(this::noOfUsersActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(noOfUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(noOfUsers))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Is the latest security patch installed?:");

        securityYes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        securityYes.setText("Yes");
        securityYes.addActionListener(this::securityYesActionPerformed);

        securityNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        securityNo.setText("No");
        securityNo.addActionListener(this::securityNoActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(securityYes)
                                .addGap(18, 18, 18)
                                .addComponent(securityNo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(securityYes)
                                        .addComponent(securityNo))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("How many 3rd party(unknown source) applications are installed?:");

        thirdPartyApps.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        thirdPartyApps.addActionListener(this::none);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(thirdPartyApps, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(thirdPartyApps))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("System Architecture in this machine:");

        architecture.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        architecture.setText("jLabel5");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(architecture, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(architecture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Which antivirus is installed?(If Linux or Mac user then select 3rd Party):");

        anitVirusThirdParty.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        anitVirusThirdParty.setText("3rd Party");
        anitVirusThirdParty.addActionListener(this::anitVirusThirdPartyActionPerformed);

        antiVirusWindows.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        antiVirusWindows.setText("Windows");
        antiVirusWindows.addActionListener(this::antiVirusWindowsActionPerformed);

        antiVirusNone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        antiVirusNone.setText("None");
        antiVirusNone.addActionListener(this::antiVirusNoneActionPerformed);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addGap(14, 14, 14)
                                .addComponent(antiVirusWindows)
                                .addGap(10, 10, 10)
                                .addComponent(anitVirusThirdParty)
                                .addGap(18, 18, 18)
                                .addComponent(antiVirusNone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(anitVirusThirdParty)
                                        .addComponent(antiVirusWindows)
                                        .addComponent(antiVirusNone))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Which browser do you normally use?:");

        chromeBrowser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chromeBrowser.setText("Chrome");
        chromeBrowser.addActionListener(this::chromeBrowserActionPerformed);

        mozillaBrowser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mozillaBrowser.setText("Mozilla");
        mozillaBrowser.addActionListener(this::mozillaBrowserActionPerformed);

        edgeBrowser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        edgeBrowser.setText("Edge");
        edgeBrowser.addActionListener(this::edgeBrowserActionPerformed);

        safariBrowser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        safariBrowser.setText("Safari");
        safariBrowser.addActionListener(this::safariBrowserActionPerformed);

        otherBrowser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        otherBrowser.setText("Other");
        otherBrowser.addActionListener(this::otherBrowserActionPerformed);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chromeBrowser)
                                .addGap(18, 18, 18)
                                .addComponent(mozillaBrowser)
                                .addGap(18, 18, 18)
                                .addComponent(edgeBrowser)
                                .addGap(18, 18, 18)
                                .addComponent(safariBrowser)
                                .addGap(18, 18, 18)
                                .addComponent(otherBrowser)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chromeBrowser)
                                        .addComponent(mozillaBrowser)
                                        .addComponent(edgeBrowser)
                                        .addComponent(safariBrowser)
                                        .addComponent(otherBrowser))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Do you use peer to peer network?:");

        p2pYes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        p2pYes.setText("Yes");
        p2pYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2pYesActionPerformed(evt);
            }
        });

        p2pNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        p2pNo.setText("No");
        p2pNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2pNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(p2pYes)
                                .addGap(18, 18, 18)
                                .addComponent(p2pNo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(p2pYes)
                                        .addComponent(p2pNo))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        submit.setText("Submit");
        submit.addActionListener(this::submitActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(364, 364, 364))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void chromeBrowserActionPerformed(java.awt.event.ActionEvent evt) {
        if (chromeBrowser.isSelected()){
            mozillaBrowser.setSelected(false);
            otherBrowser.setSelected(false);
            edgeBrowser.setSelected(false);
            safariBrowser.setSelected(false);
            j1.setBrowser("Chrome");
        }
    }

    private void antiVirusNoneActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (antiVirusNone.isSelected()){
            antiVirusWindows.setSelected(false);
            anitVirusThirdParty.setSelected(false);
            j1.setAntivirus("None");
        }
    }

    private void antiVirusWindowsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (antiVirusWindows.isSelected()){
            antiVirusNone.setSelected(false);
            anitVirusThirdParty.setSelected(false);
            j1.setAntivirus("Windows");
        }

    }

    private void anitVirusThirdPartyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (anitVirusThirdParty.isSelected()){
            antiVirusWindows.setSelected(false);
            antiVirusNone.setSelected(false);
            j1.setAntivirus("Third");
        }
    }

    private void securityYesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (securityYes.isSelected()){
            securityNo.setSelected(false);
            j1.setSecurity("Yes");
        }
    }

    private void firewallYesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (firewallYes.isSelected()){
            firewallNo.setSelected(false);
            j1.setFirewall("Yes");
        }
    }

    private void passWdNoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(passWdNo.isSelected()){
            passWdYes.setSelected(false);
            j1.setPasswd("No");
        }
    }

    private void passWdYesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(passWdYes.isSelected()){
            passWdNo.setSelected(false);
            j1.setPasswd("Yes");
        }
    }

    private void p2pYesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (p2pYes.isSelected()){
            p2pNo.setSelected(false);
            j1.setp2p("Yes");
        }
    }

    private void mozillaBrowserActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:\
        if (mozillaBrowser.isSelected()){
            chromeBrowser.setSelected(false);
            edgeBrowser.setSelected(false);
            safariBrowser.setSelected(false);
            otherBrowser.setSelected(false);
            j1.setBrowser("Mozilla");
        }
    }

    private void edgeBrowserActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (edgeBrowser.isSelected()){
            chromeBrowser.setSelected(false);
            mozillaBrowser.setSelected(false);
            safariBrowser.setSelected(false);
            otherBrowser.setSelected(false);
            j1.setBrowser("Edge");
        }
    }

    private void safariBrowserActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (safariBrowser.isSelected()){
            chromeBrowser.setSelected(false);
            edgeBrowser.setSelected(false);
            mozillaBrowser.setSelected(false);
            otherBrowser.setSelected(false);
            j1.setBrowser("Safari");
        }
    }

    private void otherBrowserActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (otherBrowser.isSelected()){
            chromeBrowser.setSelected(false);
            edgeBrowser.setSelected(false);
            safariBrowser.setSelected(false);
            mozillaBrowser.setSelected(false);
            j1.setBrowser("Other");
        }
    }

    private void p2pNoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (p2pNo.isSelected()){
            p2pYes.setSelected(false);
            j1.setp2p("No");
        }
    }

    private void securityNoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (securityNo.isSelected()){
            securityYes.setSelected(false);
            j1.setSecurity("No");
        }
    }

    private void firewallNoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (firewallNo.isSelected()){
            firewallYes.setSelected(false);
            j1.setFirewall("No");
        }
    }

    private void noOfUsersActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String selectedValue = Objects.requireNonNull(noOfUsers.getSelectedItem()).toString();
        j1.setNoofUsers(selectedValue);
    }

    private void none(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:



    }
    /*Here is the main functioning of the GUI with the submit button
    * As soon as you click the button the application will check for the errors in input
    * After that the enginerun function is called */
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {

        String s = thirdPartyApps.getText();
        Rete engine = new Rete();
        int tpApps = 0;
        try{
            tpApps = Integer.parseInt(s);
        }
        catch (NumberFormatException e){
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Please Enter Number in No. of 3rd Party Apps", "Error", JOptionPane.ERROR_MESSAGE);
        }

        try {
            // TODO add your handling code here:

            engineRun(j1.getAntivirus(), j1.getBrowser(), j1.getFirewall(), j1.getNoofUsers(), j1.getPasswd(), j1.getSecurity(), j1.getSystem(), j1.getp2p(), j1.getsysArchitecture(), tpApps, engine);
        } catch (JessException ex) {
            Logger.getLogger(pr2_DiveshBadod.class.getName()).log(Level.SEVERE, null, ex);
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Engine Not Running", "Score Evaluation", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | InstantiationException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pr2_DiveshBadod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            pr2_DiveshBadod j = new pr2_DiveshBadod();

            j.setVisible(true);

        });
    }
    /*
    * This is the function which will run the Jess engine via Rete Algorithm
    * */
    private void engineRun(String antivirus, String browser, String firewall,
                           String noofusers, String passwd, String security, String system,
                           String p2p, String sysarchitecture, int thirdparty, Rete engine)
            throws JessException{
        engine.reset();
        //Binding the rules with the algorithm
        engine.batch("rules.clp");
        //the following statements will assert the values of the metrics chosen by the user
        // in the same order written below using Rete algorithm
        engine.executeCommand("(assert(antivirus (value "+antivirus+")))");
        engine.executeCommand("(assert(browser (value "+browser+")))");
        engine.executeCommand("(assert(firewall (value "+firewall+")))");
        engine.executeCommand("(assert(noofusers (value "+noofusers+")))");
        engine.executeCommand("(assert(password (value "+passwd+")))");
        engine.executeCommand("(assert(security (value "+security+")))");
        engine.executeCommand("(assert(system (value "+system+")))");
        engine.executeCommand("(assert(p2p (value "+p2p+")))");
        engine.executeCommand("(assert(sysarchitecture (value "+sysarchitecture+")))");
        engine.executeCommand("(assert(thirdparty (value "+thirdparty+")))");
//        engine.eval("(deffunction mul (?n ?a) (return (* ?n ?a)))");
//        Value v = engine.eval("(mul 3 4)");
//        System.out.println(v.intValue(engine.getGlobalContext()));
        //This is the memory marker object which will mark the last known position of the engine
        WorkingMemoryMarker marker = engine.mark();
        engine.resetToMark(marker);
        //The engine then runs its rules based on the inputs asserted above
        engine.run();
        double antiVirusRating = Double.parseDouble(engine.getGlobalContext().getVariable("*anti*").stringValue(null));
        double browserRating = Double.parseDouble(engine.getGlobalContext().getVariable("*brow*").stringValue(null));
        double firewallRating = Double.parseDouble(engine.getGlobalContext().getVariable("*firew*").stringValue(null));
        double nouRating = Double.parseDouble(engine.getGlobalContext().getVariable("*nou*").stringValue(null));
        double passwdRating = Double.parseDouble(engine.getGlobalContext().getVariable("*passwd*").stringValue(null));
        double securityRating = Double.parseDouble(engine.getGlobalContext().getVariable("*secure*").stringValue(null));
        double systemRating = Double.parseDouble(engine.getGlobalContext().getVariable("*sys*").stringValue(null));
        double p2pRating = Double.parseDouble(engine.getGlobalContext().getVariable("*p2p*").stringValue(null));
        double architectureRating = Double.parseDouble(engine.getGlobalContext().getVariable("*arch*").stringValue(null));
        double thirdpartyRating = Double.parseDouble(engine.getGlobalContext().getVariable("*tp*").stringValue(null));
        double SystemSecurityRating = ((0.3*systemRating) + (0.2*architectureRating) + (0.5*passwdRating))/100;
        double NetworkSecurityRating = ((0.4*firewallRating) + (0.3*securityRating) + (0.3*p2pRating))/100;
        double DataSecurityRating = ((antiVirusRating*0.3) + (0.2*browserRating) + (0.4*thirdpartyRating) + (0.1*nouRating))/100;
//        engine.eval("(deffunction system (?sys) (return (* 3.33 ?sys)))");
//        Value v = engine.eval("(system 4)");
//        System.out.println(v.intValue(engine.getGlobalContext()));
//        engine.eval("(deffunction data (?sys) (return (* 3.34 ?sys)))");
//        Value v1 = engine.eval("(data DataSecurityRating)");
//        System.out.println(v1.intValue(engine.getGlobalContext()));
//        engine.eval("(deffunction network (?sys) (return (* 3.33 ?net)))");
//        Value v2 = engine.eval("(network NetworkSecurityRating)");
//        System.out.println(v2.intValue(engine.getGlobalContext()));
        //output to the above rules will work as input to the statements executed below
        engine.executeCommand("(assert(systemsecurity (value "+SystemSecurityRating+")))");
        engine.executeCommand("(assert(datasecurity (value "+DataSecurityRating+")))");
        engine.executeCommand("(assert(networksecurity (value "+NetworkSecurityRating+")))");
        //Again checking the rule engine position
        WorkingMemoryMarker m1 = engine.mark();
        engine.resetToMark(m1);
        //the rules for the following hierarchy is excuted and the value is calculated
        engine.run();
        double ss = Double.parseDouble(engine.getGlobalContext().getVariable("*ss*").stringValue(null));
        double ds = Double.parseDouble(engine.getGlobalContext().getVariable("*ds*").stringValue(null));
        double ns = Double.parseDouble(engine.getGlobalContext().getVariable("*ns*").stringValue(null));
        engine.executeCommand("(assert(totalsecurity (system "+ss+")(data "+ds+")(network "+ns+")))");
        WorkingMemoryMarker m2 = engine.mark();
        engine.resetToMark(m2);
        engine.run();
        double score = Double.parseDouble(engine.getGlobalContext().getVariable("*t*").stringValue(null));
        JFrame f = new JFrame();
        String s;
        if (score >=8.5){
            s = "Security Evaluation Score HIGH";
        }else if (score < 8.5 && score > 5){
            s = "Security Evaluation Score MEDIUM";
        }
        else{
            s = "Security Evaluation Score LOW";
        }
        JOptionPane.showMessageDialog(f, score, s, JOptionPane.INFORMATION_MESSAGE);

    }

    JavaApplication1 j1;
    // Variables declaration - do not modify
    private javax.swing.JLabel SystemName;
    private javax.swing.JRadioButton anitVirusThirdParty;
    private javax.swing.JRadioButton antiVirusNone;
    private javax.swing.JRadioButton antiVirusWindows;
    private javax.swing.JLabel architecture;
    private javax.swing.JRadioButton chromeBrowser;
    private javax.swing.JRadioButton edgeBrowser;
    private javax.swing.JRadioButton firewallNo;
    private javax.swing.JRadioButton firewallYes;
    private javax.swing.JRadioButton mozillaBrowser;
    private javax.swing.JComboBox<String> noOfUsers;
    private javax.swing.JRadioButton otherBrowser;
    private javax.swing.JRadioButton p2pNo;
    private javax.swing.JRadioButton p2pYes;
    private javax.swing.JRadioButton passWdNo;
    private javax.swing.JRadioButton passWdYes;
    private javax.swing.JRadioButton safariBrowser;
    private javax.swing.JRadioButton securityNo;
    private javax.swing.JRadioButton securityYes;
    private javax.swing.JTextField thirdPartyApps;
    // End of variables declaration
}





